x-veld:
  chain:
    description: "removes all lines before and after given line numbers"
    topic: 
      - "NLP"
      - "Preprocessing"
      - "ETL"

services:
  veld_preprocess_strip:
    build: ./code/veld_chain__preprocessing/
    volumes:
      - ./code/veld_chain__preprocessing/:/veld/code/:z
      - ./data/veld_data__amc_we_training_data/203_vert_rftt_inhalt_nodup__uniq/:/veld/input/:z
      - ./data/veld_data__amc_we_training_data/203_vert_rftt_inhalt_nodup__uniq__stripped/:/veld/output/:z
    command: bash /veld/code/strip.sh
    environment:
      in_file: "data.txt"
      out_file: "data.txt"
      line_start: 54993
      line_end: 521781020

