x-veld:
  chain:
    description: "removes all lines before and after given line numbers"
    topic: 
      - "NLP"
      - "Preprocessing"
      - "ETL"

services:
  veld_preprocess_strip:
    build: ./code/preprocessing_strip/
    volumes:
      - ./code/preprocessing_strip/:/veld/code/:z
      - /scratch-cbe/users/stefan.resch/veld_data__train_infer_wordembeddings_multiple_architectures__amc/203_vert_rftt_inhalt_nodup__uniq/:/veld/input/:z
      - /scratch-cbe/users/stefan.resch/veld_data__train_infer_wordembeddings_multiple_architectures__amc/203_vert_rftt_inhalt_nodup__uniq__stripped/:/veld/output/:z
    command: bash /veld/code/strip.sh
    environment:
      in_file: "data.txt"
      out_file: "data.txt"
      line_start: 54993
      line_end: 521781020

